### ISSUE TITLE
Combining like terms

### ISSUE THREAD

**Issue by emsal0** [gogotanaka/hilbert#14]
`
irb(main):008:0> (3*x + 4*x).to_s
`
`
=> "( x * 7 )"
`
`
irb(main):009:0> (3*x + 4*(x^2)+ 4*x).to_s
`
`
=> "( ( ( 3 * x ) + ( 4 * ( x ^ 2 ) ) ) + ( 4 * x ) )"
`

**Comment by gogotanaka** [comment]
@AbsoluteZero2A03 thank you!!

I really appriciate you.

I try to fix it.

**Comment by gogotanaka** [comment]
@AbsoluteZero2A03 

修正しました！（ver. 0.1.28）

(3_x + 4_(x^2)+ 4*x)
=> ( ( 7 \* x ) + ( 4 \* ( x ^ 2 ) ) )
