### ISSUE TITLE
Substitute bug

### ISSUE THREAD

**Issue by huyu398** [gogotanaka/hilbert#21]
``` ruby
[1] pry(main)> f(t) <= tan(t)
[2] pry(main)> f(2)
SyntaxError: (eval):1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
2an( 2 )
   ^
```

変数の代入処理を単純な文字置換で行なっているため， t のような三角関数に使われているアルファベットで変数を定義すると，エラーが発生します．
変数は x, y, z のみとする仕様でも構わないと思いますが， t や s はよく変数として定義されるアルファベットなので，何か対策を考えたほうがいいかもしれません．

**Comment by gogotanaka** [comment]
@huyu398 

これはなるほど。。
- 変数に関しては先日の`e`と同じ様に、必ず左右にスペースを入れる事を担保すか
- 変数としてsymbolを使用しているのをそもそも改める`Var` クラス的なのを導入するか
- Symbol#to_sをoverrideいして何か特別な施しを加えるか

ですね

**Comment by gogotanaka** [comment]
これについては僕が引き取ります. assigneeを僕にしておきます.

**Comment by gogotanaka** [comment]
@huyu398 さんをCollaboratorにしておきました！！

これからも宜しくお願い致します.

**Comment by huyu398** [comment]
@gogotanaka 

> @huyu398 さんをCollaboratorにしておきました！！
> 
> これからも宜しくお願い致します.

ありがとうございます．
微力ながら，協力させて頂きます．
