### ISSUE TITLE
^より+の方が演算子の優先順位が高い

### ISSUE THREAD

**Issue by hiromiso** [gogotanaka/hilbert#23]
^より+の演算子の優先順位が高いため、次のように括弧でくくられてしまいます。

```
irb(main):004:0> ( 1 + x^2 ).to_s
=> "( ( 1 + x ) ^ 2 )"
```

^の代わりに**が使えるとうれしいです。

**Comment by gogotanaka** [comment]
@hiromiso こちら、承知致しました.

**Comment by gogotanaka** [comment]
報告ありがとうございます！！！

**Comment by gogotanaka** [comment]
こちら、演算子の優先順位を書き換えるのは困難が多くある事が分かったので、

このgemでは`^` ではなく `**` を使う方に倒します.

今後の構想としてsyntaxが固まり次第、字句解析をScala辺りで実装したいと思っているので、

その時は`^` をやはり使いたいです.

**Comment by gogotanaka** [comment]
大変遅ればせながら、修正させて頂きました！

https://github.com/gogotanaka/dydx/pull/32

ver 0.1.4 としてリリース済みです.
