### ISSUE TITLE
Logic: P is TRUE but (~P)? is UNDEFINED

### ISSUE THREAD

**Issue by anton-trunov** [gogotanaka/hilbert#70]
P
Defined: P is TRUE
(~P)?
(~P) is UNDEFINED

**Comment by gogotanaka** [comment]
Thank for reporting! I've fixed it here https://github.com/gogotanaka/Hilbert/commit/42a7f95d5aec006e52bf0411866225d2a7e0bad7

And you can confirm it by updating to v0.0.2700300

https://github.com/gogotanaka/Hilbert/releases/tag/v0.0.2700300

thanks.

**Comment by anton-trunov** [comment]
Yes, it works now. Thank you.
